config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    mapping do
      # ...
    end

    def self.search(query)
      # ...
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token
  before_save   :downcase_email
  before_create :create_activation_digest
	validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }, allow_blank: true

    # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token =  User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
end
  

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = "Account activated!"
      redirect_to user
    else
      flash[:danger] = "Invalid activation link"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def show
  	@user = User.find(params[:id])

  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
    	#UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end


    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in first."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Welcome to Go-Online"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{page_title} | #{base_title}"                 # String interpolation
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
		flash[:success] = "Welcome Back!"
	end

	# Remembers a user in a persistent session.
  	def remember(user)
    	user.remember
    	cookies.permanent.signed[:user_id] = user.id
    	cookies.permanent[:remember_token] = user.remember_token
  	end

    def current_user?(user)
      user == current_user
    end



	def current_user
		if (user_id = session[:user_id])
      		@current_user ||= User.find_by(id: user_id)
    	elsif (user_id = cookies.signed[:user_id])
    		user = User.find_by(id: user_id)
    	if user && user.authenticated?(:remember, cookies[:remember_token])
     	   log_in user
     	   @current_user = user
    	end
    	end
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end	

	# Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] =  request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <span class="fa-stack fa-2x">
      <a href="https://www.twitter.com/sandeep_cm">
      <i class="fa fa-twitter"></i>
      </a>
    </span>

    <span class="fa-stack fa-2x">
      <a href="https://www.facebook.com">
      <i class="fa fa-facebook-official"></i>
      </a>
    </span>

    <span class="fa-stack fa-2x">
      <a href="https://www.linkedin.com">
      <i class="fa fa-linkedin"></i>
      </a>
    </span>
  </small>
  
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Go-Online", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
 I am a freelance web designer with over 5 years of experience in Web applications. 
'Simple and Effective' is the motto of my designs. Understanding the intricacies in a website and making it beautiful so that it catches the visitors eye is what I do best. Passionate about leveraging cutting edge technology to build light and fast websites.
</p>

<p> This is a sample website. This line breaks validation, and the Google Chrome Frame part won't work inside a conditional comment. To avoid these edge case issues it is recommended that you remove this line and use the .htaccess (or other server config) to send these headers instead. You also might want to read Validating: X-UA-Compatible. This is a sample website.</p>

<p>This is a sample website. The shortcut icons should be put in the root directory of your site. HTML5 Boilerplate comes with a default set of icons (include favicon and Apple Touch Icons) that you can use as a baseline to create your own. This is a sample website.

If your site or icons are in a sub-directory, you will need to reference the icons using link elements placed in the HTML head of your document.

For a comprehensive overview, please read Everything you always wanted to know about touch icons by Mathias Bynens. This is a sample website. This is a sample website.</p>

app/views/static_pages/contact.html.erb
<div>
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
<p>
Any Questions? Feel free to contact
</p>

<h5>Operating Hours</h5>
<u10>
<a><li>Monday to Friday 9.00 am - 9.00 pm</li></a>
<a><li>Saturday & Sunday 10.00 am - 5.00 pm</li></a>
<a><li>Public Holidays? Give us a call on Mobile </li></a>
</u10>

<p>
  <h5>Email</h5>
  <a href="mailto:sandeep.matanavar@gmail.com">sandeep.matanavar@gmail.com</a>
</p>
<p>
  <h5>Call</h5>
  <a>0469704156</a>
</p>
<p>
  <h5>Website</h5>
  <a href="http://www.go-online.herokuapp.com">www.go-online.herokuapp.com</a>
</p>


<form action="/my-handling-form-page" method="post">
  <h5>Contact Form</h5>
  <div class="container-fluid">
    <div class="row">
    <div class="col-md-6">
    <div>
        <label for="name">Name:</label>
        <input type="text" id="name" />
    </div>
    <div>
        <label for="mail">E-mail:</label>
        <input type="email" id="mail" />
    </div>
    <div>
        <label for="msg">Message:</label>
        <textarea id="msg"></textarea>
    </div>
    <div class="button">
        <%= link_to "Send Message", '#', class: "btn btn-primary", type: "submit" %>
    </div>
  </div>
</div>
</div>
</form>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  The Google CDN version of the jQuery JavaScript library is referenced towards the bottom of the page using a protocol-independent path (read more about this in the FAQ). A local fallback of 
  <a href="http://www.google.com/">jQuery</a>.
  is included for rare instances when the CDN version might not be available, and to facilitate
  <a href="http://www.google.com/"><em>offline development.</em>
  book</a>.
</p>

<p>
Regardless of which JavaScript library you choose to use, it is well worth the time and effort to look up and reference the Google CDN (Content Delivery Network) version. Your users may already have this version cached in their browsers, and Google's CDN is likely to deliver the asset faster than your server.
</p>

<p>
Finally, an optimized version of the latest Google Analytics tracking code is included. Google recommends that this script be placed at the top of the page. Factors to consider: if you place this script at the top of the page, you’ll be able to count users who don’t fully load the page, and you’ll incur the max number of simultaneous connections of the browser.
</p>

app/views/static_pages/home.html.erb
  <div class="container">
  
    <nav1>
      <ul class="nav navbar-nav navbar-left">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-th-list"></i>
              Services  <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
             <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
              <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
               <li> <%= link_to "Submenu1", '#' %> </li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-heart"></i>
              Testimonials  <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
             <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
              <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
               <li> <%= link_to "Submenu1", '#' %> </li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-truck"></i>
              Vehicles  <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
             <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
              <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
               <li> <%= link_to "Submenu1", '#' %> </li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-usd"></i>
              Pricing  <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
             <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
              <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
               <li> <%= link_to "Submenu1", '#' %> </li>
            </ul>
          </li> 


           <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-users"></i>
              Customers  <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
             <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
              <li> <%= link_to "Submenu1", '#' %> </li>
              <li class="divider"></li>
               <li> <%= link_to "Submenu1", '#' %> </li>
            </ul>
          </li> 


           <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-university"></i>
              Company  <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to "About Us", '#' %> </li>
              <li class="divider"></li>
             <li> <%= link_to "Team", '#' %> </li>
              <li class="divider"></li>
              <li> <%= link_to "Careers", '#' %> </li>
              <li class="divider"></li>
               <li> <%= link_to "Press", '#' %> </li>
            </ul>
          </li> 


          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-phone"></i>
              Contact  <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to "Call 04894483839", '#' %> </li>
              <li class="divider"></li>
             <li> <%= link_to "Email sandeep.asfd@asdf.com", '#' %> </li>
            </ul>
          </li>

      </ul>
    </nav1>

  </div>


<div class="center jumbotron"> 
  <h1>Welcome to Go-Online</h1>

  <h2>
    Simple and Effective 
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary", alt: "Sign up now!" %>
  
</div>




<div class="container">
    <div class="row">
        <div class="span4">
            <h3>How Can I help?</h3> 
            <p> 
                Do you have a business and wish to take it online? Here is what we could do, 
				<li>Discuss the business requirements of yours over a cup of coffee or via Skype/Gtalk or any other mediums. Note that I am currently based in Canberra but I can visit Sydney. </li>
				<li>After brainstorming on the design, I will propose a design on the things that would be available on the website. </li>
				<li>If you are happy, we can take it forward and deliver your website within an agreed duration of time.</li>
				</p>
				<p>
				I am a freelance web designer with over 5 years of experience in Web applications. 
				'Simple and Effective' is the motto of my designs. Understanding the intricacies in a website and making it beautiful so that it catches the visitors eye is what I do best. Passionate about leveraging cutting edge technology to build light and fast websites. 
			</p>
				<p>
				Basic website cost starts from $300. Depending on the features, cost goes up. Click <a><%= link_to "here", contact_path %></a> for Contact and more information

            </p>
        </div>  
        </div>  
    </div>  

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <i class="fa fa-user fa-fw"></i>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <i class="fa fa-envelope-o fa-fw"></i>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <i class="fa fa-key fa-fw"></i>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <i class="fa fa-key fa-fw"></i>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <i class="fa fa-user fa-fw"></i>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <i class="fa fa-envelope-o fa-fw"></i>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <i class="fa fa-key fa-fw"></i>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <i class="fa fa-key fa-fw"></i>
      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>